# Assigment 2 (week 3)

In [12]:
import numpy as np

## Implementation part

I) Implement the back substitution algorithm (neither using the forward one, nor Gaussian elimination) for upper triangular matrices.

Test it to solve $AV=b$ with the provided $A$ and $b$. **Verify the results!**

In [13]:
def back_substitution(A,b): 
    N = len(b) 
    V = np.ones(N) 
    for i in range(N-1, -1, -1): 
        what = 0 
        for j in range(N-1, i, -1): 
            what += A[i][j] * V[j] 
        V[i] = (b[i] - what) / A[i][i] 
    return V 

In [14]:
A   = np.array([[2,8,7],[0,3,1],[0,0,3]]) 
b   = np.array([4,2,6]) 
V = back_substitution(A,b) 
print("V = ", V) 
print("UV = ", np.matmul(A,V), "b = ", b) 

V =  [-5.  0.  2.]
UV =  [4. 2. 6.] b =  [4 2 6]


In [15]:
N = 10

A = np.eye(N)
for i in range(1,N):
    A += np.diag(np.ones(N-i)/N**i,i)
print("Matrix A:\n", A,"\n")

b = np.ones(N)
print("Vector b:\n",b)

Matrix A:
 [[1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05 1.e-06 1.e-07 1.e-08 1.e-09]
 [0.e+00 1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05 1.e-06 1.e-07 1.e-08]
 [0.e+00 0.e+00 1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05 1.e-06 1.e-07]
 [0.e+00 0.e+00 0.e+00 1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05 1.e-06]
 [0.e+00 0.e+00 0.e+00 0.e+00 1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e+00 1.e-01 1.e-02 1.e-03 1.e-04]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e+00 1.e-01 1.e-02 1.e-03]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e+00 1.e-01 1.e-02]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e+00 1.e-01]
 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 1.e+00]] 

Vector b:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
V = back_substitution(A,b) 
print("V = ", V) 
print("AV = ", np.dot(A,V)) 

V =  [0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 1. ]
AV =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Written part
The rest requires no implementation, you are allowed to write your answers on a different document (pdf, png, ...) if you are not confortable with markdown.

II) a) Using the Gaussian algorithm, solve  (**write** the solution ; no implementation) the problem $BV = b$, with $$ B = \left(\begin{array}{lll} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9\end{array} \right), \qquad b = \left(\begin{array}{c} 1 \\ 2 \\ 3\end{array}\right) $$

**Answer**:

b) Using the Gaussian algorithm with pivot, solve (**write** the solution ; no implementation) the problem $CV = b$, with $$ C = \left(\begin{array}{lll} 1 & 2 & 3 \\ 4 & 8 & 6 \\ 7 & 8 & 9 \end{array} \right), \qquad b = \left(\begin{array}{c} 1 \\ 2 \\ 3\end{array}\right) $$

**Answer**:

III) Using the LU decomposition algorithm, **write** down (no implementation) the lower $L$ and upper $U$ triangular matrices such that $LU = D$ with $L_{i,i} = 1$ for all $i$ and $$D = \left( \begin{array}{ccc} 1 & 2 & 0 \\ 2 & 8 & 5 \\ 0 & 8 & 19\end{array} \right).$$

**Answer:**